SPECIFICATION = "01_specification"
REQUIREMENT_ANALYSIS = "02_requirement_analysis"
TEST_SCENARIOS = "03_test_scenarios"
TEST_EVALUATION = "04_test_evaluation"
PLAYWRIGHT_AUTOMATION = "05_playwright_automation"
PLAYWRIGHT_RESULTS = "06_playwright_results"
AUTOMATION_REVIEW = "07_automation_review"